export const GET_ENTRY = 'GET_ENTRY';
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS';
export const GET_ENTRY_FAILURE = 'GET_ENTRY_FAILURE';
export const LIST_ENTRIES = 'LIST_ENTRIES';
export const LIST_ENTRIES_FAILURE = 'LIST_ENTRIES_FAILURE';
export const LIST_ENTRIES_SUCCESS = 'LIST_ENTRIES_SUCCESS';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
